package com.inverse2.rendezvous.model;
// Generated Apr 6, 2009 5:27:32 PM by Hibernate Tools 3.2.4.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Building generated by hbm2java
 */
public class Building  implements java.io.Serializable {


     private Integer buildingId;
     private LkCountryCode lkCountryCode;
     private String buildingName;
     private String address1;
     private String address2;
     private String address3;
     private String town;
     private String postcode;
     private Date activeFrom;
     private Date activeUntil;
     private Set floors = new HashSet(0);

    public Building() {
    }

	
    public Building(LkCountryCode lkCountryCode) {
        this.lkCountryCode = lkCountryCode;
    }
    public Building(LkCountryCode lkCountryCode, String buildingName, String address1, String address2, String address3, String town, String postcode, Date activeFrom, Date activeUntil, Set floors) {
       this.lkCountryCode = lkCountryCode;
       this.buildingName = buildingName;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.town = town;
       this.postcode = postcode;
       this.activeFrom = activeFrom;
       this.activeUntil = activeUntil;
       this.floors = floors;
    }
   
    public Integer getBuildingId() {
        return this.buildingId;
    }
    
    public void setBuildingId(Integer buildingId) {
        this.buildingId = buildingId;
    }
    public LkCountryCode getLkCountryCode() {
        return this.lkCountryCode;
    }
    
    public void setLkCountryCode(LkCountryCode lkCountryCode) {
        this.lkCountryCode = lkCountryCode;
    }
    public String getBuildingName() {
        return this.buildingName;
    }
    
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }
    public String getTown() {
        return this.town;
    }
    
    public void setTown(String town) {
        this.town = town;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public Date getActiveFrom() {
        return this.activeFrom;
    }
    
    public void setActiveFrom(Date activeFrom) {
        this.activeFrom = activeFrom;
    }
    public Date getActiveUntil() {
        return this.activeUntil;
    }
    
    public void setActiveUntil(Date activeUntil) {
        this.activeUntil = activeUntil;
    }
    public Set getFloors() {
        return this.floors;
    }
    
    public void setFloors(Set floors) {
        this.floors = floors;
    }




}


