package com.inverse2.rendezvous.model;
// Generated Apr 6, 2009 5:27:32 PM by Hibernate Tools 3.2.4.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Floor generated by hbm2java
 */
public class Floor  implements java.io.Serializable {


     private Integer floorId;
     private Building building;
     private String floorName;
     private Integer displayOrder;
     private Set rooms = new HashSet(0);

    public Floor() {
    }

    public Floor(Building building, String floorName, Integer displayOrder, Set rooms) {
       this.building = building;
       this.floorName = floorName;
       this.displayOrder = displayOrder;
       this.rooms = rooms;
    }
   
    public Integer getFloorId() {
        return this.floorId;
    }
    
    public void setFloorId(Integer floorId) {
        this.floorId = floorId;
    }
    public Building getBuilding() {
        return this.building;
    }
    
    public void setBuilding(Building building) {
        this.building = building;
    }
    public String getFloorName() {
        return this.floorName;
    }
    
    public void setFloorName(String floorName) {
        this.floorName = floorName;
    }
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }
    
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }
    public Set getRooms() {
        return this.rooms;
    }
    
    public void setRooms(Set rooms) {
        this.rooms = rooms;
    }




}


