package com.inverse2.rendezvous.model;
// Generated Apr 6, 2009 5:27:32 PM by Hibernate Tools 3.2.4.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * LkCountryCode generated by hbm2java
 */
public class LkCountryCode  implements java.io.Serializable {


     private String countryCode;
     private String countryName;
     private Set buildings = new HashSet(0);

    public LkCountryCode() {
    }

	
    public LkCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public LkCountryCode(String countryCode, String countryName, Set buildings) {
       this.countryCode = countryCode;
       this.countryName = countryName;
       this.buildings = buildings;
    }
   
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }
    public Set getBuildings() {
        return this.buildings;
    }
    
    public void setBuildings(Set buildings) {
        this.buildings = buildings;
    }




}


