package com.inverse2.rendezvous.model;
// Generated Apr 6, 2009 5:27:32 PM by Hibernate Tools 3.2.4.CR1



/**
 * Room generated by hbm2java
 */
public class Room  implements java.io.Serializable {


     private Integer roomId;
     private String roomCode;
     private String roomName;
     private Integer capacity;
     private String location;
     private Character selfService;
     private Integer floorId;

    public Room() {
    }

	
    public Room(String roomCode, String roomName) {
        this.roomCode = roomCode;
        this.roomName = roomName;
    }
    public Room(String roomCode, String roomName, Integer capacity, String location, Character selfService, Integer floorId) {
       this.roomCode = roomCode;
       this.roomName = roomName;
       this.capacity = capacity;
       this.location = location;
       this.selfService = selfService;
       this.floorId = floorId;
    }
   
    public Integer getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }
    public String getRoomCode() {
        return this.roomCode;
    }
    
    public void setRoomCode(String roomCode) {
        this.roomCode = roomCode;
    }
    public String getRoomName() {
        return this.roomName;
    }
    
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }
    public Integer getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Character getSelfService() {
        return this.selfService;
    }
    
    public void setSelfService(Character selfService) {
        this.selfService = selfService;
    }
    public Integer getFloorId() {
        return this.floorId;
    }
    
    public void setFloorId(Integer floorId) {
        this.floorId = floorId;
    }




}


